export interface Ova {
    type : string,
    title :string,
    subject : string,
    source : string ,
    rights : string,
    relation : string,
    rating : number,
    publisher : string,
    ova_file : string,
    ova : string,
    link : string,
    ovaLink : string,
    language : string,
    identifier : string,
    idOva : number,
    format : string,
    description : string,
    date : string,
    creator : string,
    coverage : string,
    contributor : string,
    keyS3 : string
}