import { Extension} from '../../models/extension.interface';


export const privatemimeTypes: Extension[]=[
{extension : "aac",extensionConverted:"audio/aac"},
{extension : "abw",extensionConverted:"application/x-abiword"},
{extension : "arc",extensionConverted:"application/octet-stream"},	
{extension : "avi",extensionConverted:"video/x-msvideo"},	
{extension : "azw",extensionConverted:"application/vnd.amazon.ebook"},	
{extension : "bin",extensionConverted:"application/octet-stream"},	
{extension : "bz",extensionConverted:"application/x-bzip"},
{extension : "bz2",extensionConverted:"application/x-bzip2"},	
{extension : "csh",extensionConverted:"application/x-csh"},
{extension : "css",extensionConverted:"text/css"},	
{extension : "csv",extensionConverted:"text/csv"},	
{extension : "doc",extensionConverted:"application/msword"},	
{extension : "epub",extensionConverted:"application/epub+zip"},	
{extension : "gif",extensionConverted:"image/gif"},
{extension : "html",extensionConverted:"text/html"},	
{extension : "ico",extensionConverted:"image/x-icon"},	
{extension : "ics",extensionConverted:"text/calendar"},	
{extension : "jar",extensionConverted:"application/java-archive"},
{extension : "jpeg",extensionConverted:"image/jpeg"},
{extension : "png",extensionConverted:"image/png"},
{extension : "PNG",extensionConverted:"image/png"},
{extension : "jpg",extensionConverted:"image/jpeg"},
{extension : "js",extensionConverted:"application/javascript"},
{extension : "json",extensionConverted:"application/json"},	
{extension : "mid",extensionConverted:"audio/mid"},
{extension : "midi",extensionConverted:"audio/midi"},	
{extension : "mpeg",extensionConverted:"video/mpeg"},	
{extension : "mpkg",extensionConverted:"application/vnd.apple.installer+xml"},	
{extension : "odp",extensionConverted:"application/vnd.oasis.opendocument.presentation"},
{extension : "ods",extensionConverted:"application/vnd.oasis.opendocument.spreadsheet"},	
{extension : "odt",extensionConverted:"application/vnd.oasis.opendocument.text"},
{extension : "oga",extensionConverted:"audio/ogg"},
{extension : "ogv",extensionConverted:"video/ogg"},
{extension : "ogx",extensionConverted:"application/ogg"},
{extension : "pdf",extensionConverted:"application/pdf"},	
{extension : "ppt",extensionConverted:"application/vnd.ms-powerpoint"},	
{extension : "rar",extensionConverted:"application/x-rar-compressed"},
{extension : "rtf",extensionConverted:"application/rtf"},	
{extension : "sh",extensionConverted:"application/x-sh"},
{extension : "svg",extensionConverted:"image/svg+xml"},
{extension : "swf",extensionConverted:"application/x-shockwave-flash"},	
{extension : "tar",extensionConverted:"application/x-tar"},	
{extension : "tif",extensionConverted:"image/tiff"},
{extension : "tiff",extensionConverted:"image/tiff"},	
{extension : "ttf",extensionConverted:"font/ttf"},	
{extension : "vsd",extensionConverted:"application/vnd.visio"},	
{extension : "wav",extensionConverted:"audio/webm"},	
{extension : "weba",extensionConverted:"audio/webm"},	
{extension : "webm",extensionConverted:"video/webm"},	
{extension : "webp",extensionConverted:"image/webp"},	
{extension : "woff",extensionConverted:"font/woff"},	
{extension : "woff2",extensionConverted:"font/woff2"},	
{extension : "xhtml",extensionConverted:"application/xhtml+xml"},	
{extension : "xls",extensionConverted:"application/vnd.ms-excel"},
{extension : "xml",extensionConverted:"application/xml"},	
{extension : "xul",extensionConverted:"application/vnd.mozilla.xul+xml"},
{extension : "zip",extensionConverted:"application/zip"},	
{extension : "3gp",extensionConverted:"video/3gpp"},	
{extension : "3g2",extensionConverted:"audio/3gpp2"},	
{extension : "7z",extensionConverted:"application/x-7z-compressed"}];


